### ISSUE TITLE
Email Test Results

### ISSUE THREAD

**Issue by davallerr** [mmarquiscreative/AGX_OHT_Mach2_AngularJS#2]
Hi @see8ch ,

I wanted to check on the status of emailing a person their test results and capturing their email. In a previous email Austin passed along, it sounded like you had some ideas for the kind of tools that could make it possible. Have you figured out the best way to implement it?

As a heads up, our IT team has let us know that the test results will qualify as protected health information and there are some security policies that have to be met for us to send them over email. They can review how the results are sent and let us know if there are any adjustments that need to be made to comply with those rules.

Thanks,
David

**Comment by see8ch** [comment]
I'm still leaning towards a form through the Ninja Forms plugin. This is how all of the emails are handled on Merriweather 2.0, takes care of the database as well as sending through smtp, and would be easy to hook into. You would need to add a setting that allowed a user to input a Form ID that corresponded to the form that was created in Ninja Forms. The easiest route would be a basic embed of the form and using the hooks that ninja forms provides to perform any actions after form submission. 

They have a pretty extensive [documentation](https://ninjaforms.com/documentation/) and the plugin is already active on the [agcorp multisite](https://testsite.agcorp.wpengine.com/wp-admin/admin.php?page=ninja-forms#forms)

Let me know if this looks like something that would work with your existing framework.

**Comment by mmarquiscreative** [comment]
@see8ch (Thanks for the last reply) Question of clarification from one of our IT guys — would the data be collected on an HTTPS webpage with SSL and encrypted form submission (Ideally, the database where the form submission data is collected is encrypted (or at least the hearing data collected) as well.)? 

He also shared this: https://ninjaforms.com/docs/ninja-forms-secure/

Thanks!

**Comment by see8ch** [comment]
@mmarquiscreative If we go with this solution, the emails will be sent and stored on the site the plugin you are building is running on. All of the Audigy sites have SSL and the emails are sent through the WPE SMTP protocols. Previously we were using the Audigy SMTP server for emails, but we moved away from that due to conflicts with WP Engine and blocked ports. 

The databases on WPE are not encrypted and probably won't be just due to overwhelming amount of work that would require and conflicts it would cause with their environment. There are methods of making Ninja Forms and Gravity Forms immediately dump the database record and just send the email, which has been the most secure method for some other clients. 

The recipient's email is actually the most common issue. Most companies don't actually have HIPAA compliant email servers and I would be willing to be Audigy is in that majority too. If you could check on that side and let me know if Audigy's email server is HIPAA compliant as well? If it's not, that may be the first task. There are third-party HIPAA compliant email/form providers but they are VERY costly. 

Are any of the sites that will have this plugin be on a host besides WPE? How many sites total?

**Comment by mmarquiscreative** [comment]
Ok, figured out what was happening, you can ignore the last message. 

However I do have 2 additional questions for you. :)

1. Can we only have one person logged into the SFTP using the same username at a time? If so, can I get my own log in credentials so I can work when David's logged in?

2. Our IT guy got back to us saying: "We are OK without encrypting the email as long as we take care to be in good security practice, according to the HHS, so I think we are good there: https://www.hhs.gov/hipaa/for-professionals/faq/570/does-hipaa-permit-health-care-providers-to-use-email-to-discuss-health-issues-with-patients/index.html
 
For you, would it be an issue we had Chris dump the record after sending? It is more secure, do you want to discuss with Chris how you would do any troubleshooting in case a lead was lost or you needed to track something down?"

Are there any steps we can take when dumping to check to see if the email was sent before dumping? So that if it wasn't we would get some sort of email on our end letting us know it didn't work or something?

What are your thoughts on it?

Thanks Chris!

**Comment by see8ch** [comment]
**FTP:** Here you go

- User: `agcorp-mmarquiscreative`
- Password: `K2grohd9Anakbt`
- Host: `agcorp.sftp.wpengine.com `
- Port: `2222`

**Email:** Sounds good!

**Database Dump:** This was the method I suggested above. The database submission can be skipped entirely and the emails to the user and admin would still be sent (You can read more about that here: https://ninjaforms.com/ninja-forms-feature-spotlight-save-action/). 

**Error:** If the email to the user did not send, then the admin notification would not send either. The database of submissions is the catch all solution unfortunately. The closest error message we would get if the emails did not go through would be in the server error logs. This is highly unlikely though as it would have to be something server wide that would bring down the email server and the other sites would also notice an outage. 

**Submission Method:** Ninja Forms allows for AJAX submissions or PHP (page reload). When you embed a test form, make sure to check AJAX and debug with that method first since it would be a better user experience from within a popup. 

**Misc:** Some questions from above that got skipped:

```
Are any of the sites that will have this plugin be on a host besides WPE? 
How many sites total?
```

**Comment by mmarquiscreative** [comment]
Hey man, we're getting an error with the 'volume' section of our test, where it's saying it can't find the audio file. But we weren't in there, and we noticed there was another error that said:
2(index):161 GET https://testsite.agcorp.wpengine.com/wp-content/plugins/audigy-provider-import/inc/assets/scripts/scripts-twenty.js?ver=4.9.8 net::ERR_ABORTED 404

Just wanted to see if maybe you're working in here at the same time, and something broke our preview of the test? It looks like the script referenced above is gone in the folder on the SFTP.

Thanks!

**Comment by mmarquiscreative** [comment]
It could also be this error: 
@see8ch 
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://testsite.agcorp.wpengine.com/#/stage/quiz

Not really sure why it's suddenly coming up though

**Comment by see8ch** [comment]
@mmarquiscreative Neither of those errors would be causing any issues with your volume functionality. It looks like your audio file is linked incorrectly though - https://cloudup.com/c7PPdQJNik9

**Comment by mmarquiscreative** [comment]
@see8ch Hey Chris, so I re-linked the volume correctly, and we're still experiencing a broken test. We were tentatively hoping to send this to some members for their input soon, before this issue came up. Is this something you could take a look at and see why it's braking? Currently it starts the audio right away (though it shouldn't) and the button that should start the audio isn't working.

Thanks!

**Comment by mmarquiscreative** [comment]
@see8ch HEY! Think we figured it out.

**Comment by mmarquiscreative** [comment]
@see8ch Is there a way to make the test site secure (I.e. getting an SSL certificate?) We're hoping to share this link with some key stakeholders, but they get a 'this is an unsafe site' warning.

Thanks!

**Comment by mmarquiscreative** [comment]
Hey @see8ch just checking in on my previous question about security. Thanks!

**Comment by mmarquiscreative** [comment]
@see8ch  ended up finding a host site to host the master branch, so don't worry about the SSL certificate thing. I'm going to open a new issue for the email functionality, to help keep things organized. Thanks!
